[theme]

base = 'light'

# Primary accent for interactive elements
primaryColor = '#f6956a'

# Background color for the main content area
backgroundColor = '#fefbf5'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#cbc8c3'

